import { createApp } from "vue";
import "./style.css";
import App from "./App.vue";
import router from "./router";
import BaseModal from "@/components/BaseModal.vue";
import ModalAlumno from "@/components/ModalAlumno.vue";
const app = createApp(App);
app.component("base-modal", BaseModal);
app.component("alumno-modal", ModalAlumno);
app.use(router);
app.mount("#app");
